---
before:
  hooks:
    - go mod tidy
    - go mod verify
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

archives:
  - builds_info:
      mode: 0755
    name_template: "dcjulian29.apps.ini-file_{{ .Version }}_{{ .Os }}"
    format_overrides:
      - format: zip
        goos: windows

nfpms:
  - package_name: dcjulian29.apps.ini-file
    homepage: https://github.com/dcjulian29/cli-tools/ini-file/
    maintainer: Julian Easterling <julian@julianscorner.com>
    license: Apache 2.0
    description: |-
      ini-file provides management functions.
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin

chocolateys:
  - name: dcjulian29.apps.ini-file
    authors: Julian Easterling <julian@julianscorner.com>
    project_url: https://github.com/dcjulian29/cli-tools/ini-file/
    copyright: 2023 Julian Easterling julian@julianscorner.com
    license_url: https://github.com/dcjulian29/cli-tools/blob/main/LICENSE
    require_license_acceptance: false
    bug_tracker_url: https://github.com/dcjulian29/cli-tools/issues
    description: |
      ini-file synchronizes all git repositories located within the specified path or current directory.
    skip_publish: true
    source_repo: "https://www.myget.org/F/dcjulian29-chocolatey/"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^admin:'
      - '^docs:'
      - '^test:'
