project_name: build-project
version: 2
before:
  hooks:
    - go mod tidy
    - go mod verify
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

archives:
  - builds_info:
      group: root
      owner: root
      mode: 0755
    name_template: "dcjulian29.apps.build-project_{{ .Version }}_{{ .Os }}"
    format_overrides:
      - formats: [ "zip" ]
        goos: windows

nfpms:
  - package_name: dcjulian29.apps.build-project
    homepage: https://github.com/dcjulian29/cli-tools/build-project/
    maintainer: Julian Easterling <julian@julianscorner.com>
    license: Apache 2.0
    description: |-
      build-project is a tool to abstract building a project from the specific implementation.
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin

chocolateys:
  - name: dcjulian29.apps.build-project
    authors: Julian Easterling <julian@julianscorner.com>
    project_url: https://github.com/dcjulian29/cli-tools/build-project/
    copyright: 2023 Julian Easterling julian@julianscorner.com
    license_url: https://github.com/dcjulian29/cli-tools/blob/main/LICENSE
    require_license_acceptance: false
    bug_tracker_url: https://github.com/dcjulian29/cli-tools/issues
    description: |
      build-project is a tool to abstract building a project from the specific implementation.
    skip_publish: true

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^admin:'
      - '^docs:'
      - '^test:'
