---
name: CLI Tools

'on':
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tools:
          - dns-resolve
          - dns-scan
          - doggo
          - download
          - git-repostatus
          - git-reposync
          - ini-file
          - ip-scan
          - muffet
          - unix-tools

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ github.workspace }}/${{ matrix.tools }}/go.mod

      - uses: goreleaser/goreleaser-action@v7
        with:
          args: build --snapshot
          workdir: ${{ github.workspace }}/${{ matrix.tools }}

  release:
    if: contains(github.ref, 'tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: simbo/changes-between-tags-action@v1
        id: changelog
        with:
          line-prefix: '* '

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: |
            ## Changelog
            ${{ steps.changelog.outputs.changes }}
            #### Previous Release: ${{ steps.changelog.outputs.ref }}
          make_latest: true

  package:
    if: contains(github.ref, 'tags/')
    needs: [release]
    runs-on: windows-2022

    strategy:
      matrix:
        tools:
          - dns-resolve
          - dns-scan
          - doggo
          - download
          - git-repostatus
          - git-reposync
          - ini-file
          - ip-scan
          - muffet
          - unix-tools

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ github.workspace }}/${{ matrix.tools }}/go.mod

      - uses: goreleaser/goreleaser-action@v7
        with:
          args: release --skip publish
          workdir: ${{ github.workspace }}/${{ matrix.tools }}

      - uses: NuGet/setup-nuget@v2.0.2

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ matrix.tools }}/dist/dcjulian29.*_*.*
          omitBody: true
          omitName: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: >
          dotnet nuget push ${{ matrix.tools }}/**/*.nupkg
          --api-key '${{ secrets.CHOCO_API_KEY }}'
          --source '${{ vars.CHOCO_URL }}'
          --skip-duplicate
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
