---
name: Build

'on':
  push:
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'

  pull_request:
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'

  workflow_dispatch:

jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tools:
          - dns-resolve
          - dns-scan
          - git-repostatus
          - git-reposync
          - ini-file
          - ip-scan
          - provision-test
          - unix-tools

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          go-version-file: ${{ github.workspace }}/${{ matrix.tools }}/go.mod

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: build --snapshot
          workdir: ${{ github.workspace }}/${{ matrix.tools }}
