---
name: CLI Tools

'on':
  push:
    paths:
      - .goreleaser.yaml
      - *.mod
      - *.sum
      - *.go

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tools:
          - build-project
          - dns-resolve
          - dns-scan
          - doggo
          - download
          - git-repostatus
          - git-reposync
          - ini-file
          - ip-scan
          - muffet
          - provision-test
          - unix-tools

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.workspace }}/${{ matrix.tools }}/go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          args: build --snapshot
          workdir: ${{ github.workspace }}/${{ matrix.tools }}

  release:
    if: contains(github.ref, 'tags/')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          makeLatest: true
          name: ${{ github.ref_name }}
          tag: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

  package:
    if: contains(github.ref, 'tags/')
    needs: [release]
    runs-on: windows-2022

    strategy:
      matrix:
        tools:
          - build-project
          - dns-resolve
          - dns-scan
          - doggo
          - download
          - git-repostatus
          - git-reposync
          - ini-file
          - ip-scan
          - muffet
          - provision-test
          - unix-tools

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.workspace }}/${{ matrix.tools }}/go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          args: release --skip publish
          workdir: ${{ github.workspace }}/${{ matrix.tools }}

      - uses: NuGet/setup-nuget@v2.0.0

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ matrix.tools }}/dist/dcjulian29.*_*.*
          omitBody: true
          omitName: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: >
          dotnet nuget push ${{ matrix.tools }}/**/*.nupkg
          --api-key '${{ secrets.CHOCO_API_KEY }}'
          --source '${{ vars.CHOCO_URL }}'
          --skip-duplicate
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
