---
name: Package

'on':
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

jobs:
  package:
    runs-on: windows-2022

    strategy:
      matrix:
        tools:
          - dns-resolve
          - dns-scan
          - git-repostatus
          - git-reposync
          - ip-scan
          - unix-tools

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.work

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --skip-publish
          workdir: ${{ github.workspace }}/${{ matrix.tools }}

      - uses: NuGet/setup-nuget@v1.1.1

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ matrix.tools }}/dist/dcjulian29.*_*.*
          omitBody: true
          omitName: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: >
          dotnet nuget push ${{ matrix.tools }}/**/*.nupkg
          --api-key '${{ secrets.CHOCO_API_KEY }}'
          --source '${{ vars.CHOCO_URL }}'
          --skip-duplicate
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
